---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityhub
  namespace: ${PARTICIPANT_NAME}
  labels:
    App: identityhub
spec:
  replicas: 1
  selector:
    matchLabels:
      App: identityhub
  template:
    metadata:
      labels:
        App: identityhub
    spec:
      containers:
        - name: identityhub
          image: ghcr.io/paullatzelsperger/minimumviabledataspace/identity-hub:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ih-config
          ports:
            - containerPort: 7082
              name: creds-port
            - containerPort: 1044
              name: debug
            - containerPort: 7081
              name: identity-api
            - containerPort: 7083
              name: did
            - containerPort: 7080
              name: web

          livenessProbe:
            httpGet:
              path: /api/check/liveness
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /api/check/readiness
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120
          startupProbe:
            httpGet:
              path: /api/check/startup
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ih-config
  namespace: ${PARTICIPANT_NAME}
data:
  EDC_IH_IAM_ID: "${PARTICIPANT_ID}"
  EDC_IAM_DID_WEB_USE_HTTPS: "false"
  EDC_IH_IAM_PUBLICKEY_ALIAS: "${PARTICIPANT_NAME}-publickey"
  EDC_IH_API_SUPERUSER_KEY: "c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo="
  WEB_HTTP_PORT: "7080"
  WEB_HTTP_PATH: "/api"
  WEB_HTTP_IDENTITY_PORT: "7081"
  WEB_HTTP_IDENTITY_PATH: "/api/identity"
  WEB_HTTP_IDENTITY_AUTH_KEY: "password"
  WEB_HTTP_CREDENTIALS_PORT: "7082"
  WEB_HTTP_CREDENTIALS_PATH: "/api/credentials"
  WEB_HTTP_DID_PORT: "7083"
  WEB_HTTP_DID_PATH: "/"
  WEB_HTTP_STS_PORT: "7084"
  WEB_HTTP_STS_PATH: "/api/sts"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"
  EDC_IAM_STS_PRIVATEKEY_ALIAS: "key-1"

  EDC_IAM_STS_PUBLICKEY_ID: "key-1"
  EDC_MVD_CREDENTIALS_PATH: "/etc/credentials/"

  EDC_VAULT_HASHICORP_URL: "http://vault.${PARTICIPANT_NAME}.svc.cluster.local:8200"
  EDC_VAULT_HASHICORP_TOKEN: "root"

  EDC_DATASOURCE_DEFAULT_URL: "jdbc:postgresql://postgres-service.${PARTICIPANT_NAME}.svc.cluster.local:5432/${PARTICIPANT_NAME}"
  EDC_DATASOURCE_DEFAULT_USER: "${PARTICIPANT_NAME}"
  EDC_DATASOURCE_DEFAULT_PASSWORD: "${PARTICIPANT_NAME}"
  EDC_SQL_SCHEMA_AUTOCREATE: "true"
  EDC_IAM_ACCESSTOKEN_JTI_VALIDATION: "true"
  # grace period for credential expiry, 3600*24 = 1 day
  EDC_IAM_CREDENTIAL_RENEWAL_GRACEPERIOD: "86400"

---
apiVersion: v1
kind: Service
metadata:
  name: identityhub
  namespace: ${PARTICIPANT_NAME}
spec:
  type: NodePort
  selector:
    App: identityhub
  ports:
    - port: 7082
      targetPort: 7082
      name: creds-port
    - port: 1044
      targetPort: 1044
      name: debug
    - port: 7081
      targetPort: 7081
      name: identity-api
    - port: 7083
      targetPort: 7083
      name: did
    - port: 7084
      targetPort: 7084
      name: sts

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identityhub
  namespace: ${PARTICIPANT_NAME}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /${PARTICIPANT_NAME}/cs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identityhub
                port:
                  number: 7081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: did
  namespace: ${PARTICIPANT_NAME}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/${PARTICIPANT_NAME}/$2"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /${PARTICIPANT_NAME}(/|&)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identityhub
                port:
                  number: 7083
